import { useRouter } from "expo-router";
import React, { useState } from "react";
import {
  Alert,
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Button, Input } from "../../src/components/ui";
import { colors, spacing, typography } from "../../src/constants/theme";
import { useAuth } from "../../src/context";
import { acceptInvite } from "../../src/services/auth.service";

export default function AcceptInviteScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { refreshUser } = useAuth();

  const [inviteId, setInviteId] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");
  const [registrationNo, setRegistrationNo] = useState("");
  const [specialization, setSpecialization] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const validate = () => {
    const e: Record<string, string> = {};
    if (!inviteId.trim()) e.inviteId = "Invite ID is required";
    if (!email.trim()) e.email = "Email is required";
    else if (!/\S+@\S+\.\S+/.test(email)) e.email = "Enter a valid email";
    if (!password) e.password = "Password is required";
    else if (password.length < 8) e.password = "Minimum 8 characters";
    if (confirmPassword !== password)
      e.confirmPassword = "Passwords do not match";
    if (!name.trim()) e.name = "Full name is required";
    if (!phone.trim()) e.phone = "Phone number is required";
    if (!registrationNo.trim())
      e.registrationNo = "Registration number is required";
    setErrors(e);
    return Object.keys(e).length === 0;
  };

  const handleAcceptInvite = async () => {
    if (!validate()) return;
    setIsLoading(true);
    try {
      await acceptInvite({
        inviteId,
        email,
        password,
        name,
        phone,
        registrationNo,
        specialization: specialization || undefined,
      });
      await refreshUser();
    } catch (e: unknown) {
      const msg =
        e instanceof Error ? e.message : "Invalid invite ID or credentials";
      Alert.alert("Activation Error", msg);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <KeyboardAvoidingView
      style={styles.flex}
      behavior={Platform.OS === "ios" ? "padding" : "height"}
    >
      <View style={[styles.container, { paddingBottom: insets.bottom }]}>
        <ScrollView
          style={styles.scroll}
          contentContainerStyle={styles.scrollContent}
          keyboardShouldPersistTaps="handled"
          showsVerticalScrollIndicator={false}
        >
          {/* ── HEADER (scrolls with content) ── */}
          <View
            style={[styles.topSection, { paddingTop: insets.top + spacing.md }]}
          >
            <View style={styles.blobTopRight} />
            <View style={styles.blobBottomLeft} />

            <TouchableOpacity
              onPress={() => router.back()}
              style={styles.backBtn}
            >
              <Text style={styles.backText}>← Back</Text>
            </TouchableOpacity>

            <View style={styles.logoMark}>
              <Text style={styles.logoEmoji}>✉️</Text>
            </View>

            <Text style={styles.heading}>
              Accept Invite<Text style={styles.headingAccent}>.</Text>
            </Text>
            <Text style={styles.subheading}>
              Join your hospital as a verified doctor
            </Text>
          </View>

          {/* ── FORM CONTENT ── */}
          <View style={styles.formContent}>
            <View style={styles.infoBanner}>
              <Text style={styles.infoBannerIcon}>💡</Text>
              <Text style={styles.infoBannerText}>
                Your Invite ID was generated by your hospital administrator.
                Check your email or contact them directly.
              </Text>
            </View>

            <Input
              label="Invite ID"
              icon="key-outline"
              placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
              value={inviteId}
              onChangeText={setInviteId}
              autoCapitalize="none"
              error={errors.inviteId}
            />

            <SectionDivider label="Account Credentials" />

            <Input
              label="Your Email"
              icon="mail-outline"
              placeholder="doctor@hospital.com"
              value={email}
              onChangeText={setEmail}
              autoCapitalize="none"
              keyboardType="email-address"
              error={errors.email}
            />
            <Input
              label="Password"
              icon="lock-closed-outline"
              placeholder="Min. 8 characters"
              value={password}
              onChangeText={setPassword}
              secureTextEntry
              secureToggle
              error={errors.password}
            />
            <Input
              label="Confirm Password"
              icon="shield-checkmark-outline"
              placeholder="Re-enter password"
              value={confirmPassword}
              onChangeText={setConfirmPassword}
              secureTextEntry
              secureToggle
              error={errors.confirmPassword}
            />

            <SectionDivider label="Medical Profile" />

            <Input
              label="Full Name"
              icon="person-outline"
              placeholder="Dr. John Doe"
              value={name}
              onChangeText={setName}
              error={errors.name}
            />
            <Input
              label="Phone Number"
              icon="call-outline"
              placeholder="+237 ..."
              value={phone}
              onChangeText={setPhone}
              keyboardType="phone-pad"
              error={errors.phone}
            />
            <Input
              label="Registration No."
              icon="card-outline"
              placeholder="Medical License Number"
              value={registrationNo}
              onChangeText={setRegistrationNo}
              error={errors.registrationNo}
            />
            <Input
              label="Specialization (Optional)"
              icon="medkit-outline"
              placeholder="e.g. Cardiologist"
              value={specialization}
              onChangeText={setSpecialization}
            />

            <Button
              title="Activate Account"
              onPress={handleAcceptInvite}
              loading={isLoading}
              disabled={isLoading}
              size="lg"
              style={styles.submitBtn}
            />

            <View style={styles.footer}>
              <Text style={styles.footerText}>Already registered? </Text>
              <TouchableOpacity onPress={() => router.push("/(auth)/login")}>
                <Text style={styles.footerLink}>Sign In</Text>
              </TouchableOpacity>
            </View>
          </View>
        </ScrollView>
      </View>
    </KeyboardAvoidingView>
  );
}

function SectionDivider({ label }: { label: string }) {
  return (
    <View style={dividerStyles.row}>
      <View style={dividerStyles.line} />
      <Text style={dividerStyles.label}>{label}</Text>
      <View style={dividerStyles.line} />
    </View>
  );
}

const ORANGE = "#F05A28";

const dividerStyles = StyleSheet.create({
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginTop: spacing.sm,
    marginBottom: -spacing.xs,
  },
  line: { flex: 1, height: 1, backgroundColor: "#E8E8F0" },
  label: {
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.bold,
    color: "#8A8A9A",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
});

const styles = StyleSheet.create({
  flex: { flex: 1 },
  container: { flex: 1, backgroundColor: "#F7F7F8" },

  scroll: { flex: 1 },
  scrollContent: { flexGrow: 1 },

  /* ── HEADER ── */
  topSection: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: spacing["2xl"],
    paddingBottom: spacing["2xl"],
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 4,
  },
  blobTopRight: {
    position: "absolute",
    top: -60,
    right: -60,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: "rgba(240,90,40,0.09)",
  },
  blobBottomLeft: {
    position: "absolute",
    bottom: -30,
    left: -30,
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: "rgba(240,90,40,0.06)",
  },

  backBtn: { marginBottom: spacing.lg },
  backText: {
    fontSize: typography.fontSize.sm,
    color: "#8A8A9A",
    fontWeight: typography.fontWeight.medium,
  },

  logoMark: {
    width: 44,
    height: 44,
    borderRadius: 13,
    backgroundColor: ORANGE,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.md,
    shadowColor: ORANGE,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 6,
  },
  logoEmoji: { fontSize: 20 },

  heading: {
    fontSize: 30,
    fontWeight: "700",
    color: "#1A1A2E",
    letterSpacing: -0.5,
    lineHeight: 34,
    marginBottom: spacing.xs,
  },
  headingAccent: { color: ORANGE },
  subheading: { fontSize: typography.fontSize.sm, color: "#8A8A9A" },

  /* ── FORM CONTENT ── */
  formContent: {
    padding: spacing["2xl"],
    gap: spacing.lg,
    paddingBottom: spacing["3xl"],
  },

  infoBanner: {
    backgroundColor: "#FFF1EB",
    borderWidth: 1,
    borderColor: "#FDE8DF",
    borderRadius: 14,
    padding: spacing.lg,
    flexDirection: "row",
    gap: spacing.sm,
    alignItems: "flex-start",
  },
  infoBannerIcon: { fontSize: 15, lineHeight: 22 },
  infoBannerText: {
    flex: 1,
    fontSize: typography.fontSize.xs,
    color: "#C04010",
    lineHeight: 20,
  },

  submitBtn: { marginTop: spacing.sm },

  footer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingTop: spacing.xs,
  },
  footerText: { fontSize: typography.fontSize.sm, color: "#8A8A9A" },
  footerLink: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.bold,
    color: ORANGE,
  },
});
