import { useRouter } from "expo-router";
import React, { useState } from "react";
import {
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Button, Card, Input } from "../../src/components/ui";
import { colors, spacing, typography } from "../../src/constants/theme";
import { useAuth } from "../../src/context";
import { acceptInvite } from "../../src/services/auth.service";

export default function AcceptInviteScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { refreshUser } = useAuth();

  const [inviteId, setInviteId] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");
  const [registrationNo, setRegistrationNo] = useState("");
  const [specialization, setSpecialization] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const validate = () => {
    const e: Record<string, string> = {};
    if (!inviteId.trim()) e.inviteId = "Invite ID is required";
    if (!email.trim()) e.email = "Email is required";
    else if (!/\S+@\S+\.\S+/.test(email)) e.email = "Enter a valid email";
    if (!password) e.password = "Password is required";
    else if (password.length < 8) e.password = "Minimum 8 characters";
    if (confirmPassword !== password)
      e.confirmPassword = "Passwords do not match";
    if (!name.trim()) e.name = "Full name is required";
    if (!phone.trim()) e.phone = "Phone number is required";
    if (!registrationNo.trim())
      e.registrationNo = "Registration number is required";

    setErrors(e);
    return Object.keys(e).length === 0;
  };

  const handleAcceptInvite = async () => {
    if (!validate()) return;
    setIsLoading(true);
    try {
      await acceptInvite({
        inviteId,
        email,
        password,
        name,
        phone,
        registrationNo,
        specialization: specialization || undefined,
      });
      await refreshUser();
    } catch (e: unknown) {
      const msg =
        e instanceof Error ? e.message : "Invalid invite ID or credentials";
      setErrors({ inviteId: msg });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <KeyboardAvoidingView
      style={styles.flex}
      behavior={Platform.OS === "ios" ? "padding" : "height"}
    >
      <View style={[styles.container, { paddingBottom: insets.bottom }]}>
        <View
          style={[styles.headerStrip, { paddingTop: insets.top + spacing.xl }]}
        >
          <TouchableOpacity
            onPress={() => router.back()}
            style={styles.backBtn}
          >
            <Text style={styles.backText}>← Back</Text>
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Accept Invite</Text>
          <Text style={styles.headerSubtitle}>
            Join your hospital as a verified doctor
          </Text>
        </View>

        <ScrollView
          style={styles.scroll}
          contentContainerStyle={styles.scrollContent}
          keyboardShouldPersistTaps="handled"
        >
          <Card padding="lg" style={styles.formCard}>
            <View style={styles.infoBox}>
              <Text style={styles.infoText}>
                💡 Your invite ID (UUID) was generated by your hospital
                administrator. Check your email or contact them directly.
              </Text>
            </View>

            <Input
              label="Invite ID"
              icon="key-outline"
              placeholder="e.g. xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
              value={inviteId}
              onChangeText={setInviteId}
              autoCapitalize="none"
              error={errors.inviteId}
            />

            <View style={styles.sectionSeparator}>
              <Text style={styles.sectionTitle}>Account Credentials</Text>
            </View>

            <Input
              label="Your Email"
              icon="mail-outline"
              placeholder="doctor@hospital.com"
              value={email}
              onChangeText={setEmail}
              autoCapitalize="none"
              keyboardType="email-address"
              error={errors.email}
            />
            <Input
              label="Password"
              icon="lock-closed-outline"
              placeholder="Min. 8 characters"
              value={password}
              onChangeText={setPassword}
              secureTextEntry
              secureToggle
              error={errors.password}
            />
            <Input
              label="Confirm Password"
              icon="shield-checkmark-outline"
              placeholder="Re-enter password"
              value={confirmPassword}
              onChangeText={setConfirmPassword}
              secureTextEntry
              secureToggle
              error={errors.confirmPassword}
            />

            <View style={styles.sectionSeparator}>
              <Text style={styles.sectionTitle}>Medical Profile</Text>
            </View>

            <Input
              label="Full Name"
              icon="person-outline"
              placeholder="Dr. John Doe"
              value={name}
              onChangeText={setName}
              error={errors.name}
            />
            <Input
              label="Phone Number"
              icon="call-outline"
              placeholder="+237 ..."
              value={phone}
              onChangeText={setPhone}
              keyboardType="phone-pad"
              error={errors.phone}
            />
            <Input
              label="Registration No."
              icon="card-outline"
              placeholder="Medical License Number"
              value={registrationNo}
              onChangeText={setRegistrationNo}
              error={errors.registrationNo}
            />
            <Input
              label="Specialization (Optional)"
              icon="medkit-outline"
              placeholder="e.g. Cardiologist"
              value={specialization}
              onChangeText={setSpecialization}
            />

            <Button
              title="Activate Account"
              onPress={handleAcceptInvite}
              loading={isLoading}
              disabled={isLoading}
              size="lg"
              style={styles.submitBtn}
            />
          </Card>

          <View style={styles.footer}>
            <Text style={styles.footerText}>Already registered? </Text>
            <TouchableOpacity onPress={() => router.push("/(auth)/login")}>
              <Text style={styles.footerLink}>Sign In</Text>
            </TouchableOpacity>
          </View>
        </ScrollView>
      </View>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  flex: { flex: 1 },
  container: { flex: 1, backgroundColor: colors.background },
  headerStrip: {
    backgroundColor: colors.primary,
    paddingHorizontal: spacing["2xl"],
    paddingBottom: spacing["3xl"],
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
  },
  backBtn: { marginBottom: spacing.xl },
  backText: {
    fontSize: typography.fontSize.sm,
    color: "rgba(255,255,255,0.8)",
    fontWeight: typography.fontWeight.medium,
  },
  headerTitle: {
    fontSize: typography.fontSize["4xl"],
    fontWeight: typography.fontWeight.bold,
    color: colors.white,
    marginBottom: spacing.sm,
  },
  headerSubtitle: {
    fontSize: typography.fontSize.base,
    color: "rgba(255,255,255,0.75)",
  },
  scroll: { flex: 1 },
  scrollContent: {
    padding: spacing["2xl"],
    paddingTop: spacing["3xl"],
    gap: spacing["2xl"],
  },
  formCard: { marginTop: -spacing["4xl"] },
  infoBox: {
    backgroundColor: colors.primaryLight,
    borderRadius: 12,
    padding: spacing.lg,
    marginBottom: spacing.xl,
  },
  infoText: {
    fontSize: typography.fontSize.sm,
    color: colors.primaryDark,
    lineHeight: 20,
  },
  sectionSeparator: {
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingBottom: spacing.xs,
  },
  sectionTitle: {
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.bold,
    color: colors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  submitBtn: { marginTop: spacing.xl },
  footer: { flexDirection: "row", justifyContent: "center" },
  footerText: { fontSize: typography.fontSize.sm, color: colors.textSecondary },
  footerLink: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.bold,
    color: colors.primary,
  },
});
